"""smooth-operator-core (Python): a native, in-process agent engine.

The Phase-0 Python sibling of the Rust reference engine and the C# core — an
agentic tool-calling loop over any OpenAI-compatible chat client, with in-memory
knowledge grounding. See ``docs/Architecture/Python Core.md``.
"""

from .agent import (
    AgentOptions,
    AgentRunResponse,
    DoneEvent,
    FunctionTool,
    SmoothAgent,
    StreamEvent,
    TextEvent,
    Tool,
    ToolCallEvent,
    ToolResultEvent,
    delegate_tool,
    effective_max_tokens,
)
from .cast import Cast, Clearance, OperatorRole, RoleKind
from .checkpoint import Checkpoint, CheckpointStore, InMemoryCheckpointStore
from .context import FileRef, load_project_context, parse_file_references
from .cost import GATEWAY_COST_HEADERS, CostBudget, CostTracker, ModelPricing, Usage, parse_gateway_cost
from .deny_policy import DenyPolicy, DenyPredicate, DenyReason, DenyRules
from .executor import (
    AgentActivities,
    AgentExecutor,
    InProcessActivities,
    InProcessExecutor,
    TurnPolicy,
    drive_turn,
)
from .gateway_client import GatewayLlmProvider
from .hooks import ToolCall, ToolHook, ToolResult
from .human_gate import (
    DelegateHumanGate,
    HumanApprovalRequest,
    HumanApprovalResponse,
    HumanDecision,
    HumanGate,
)
from .knowledge import InMemoryKnowledge, Knowledge, KnowledgeHit
from .llm_provider import (
    LlmProvider,
    MockLlmProvider,
    RecordedCall,
    scripted_usage,
    text_response,
    tool_call_response,
    usage,
)
from .memory import InMemoryMemory, Memory, MemoryEntry
from .narc import (
    NarcAlert,
    NarcFinding,
    NarcHook,
    Severity,
    has_injection,
    has_secrets,
    redact_match,
    scan_injection,
    scan_secrets,
)
from .permission import (
    Allow,
    Ask,
    AutoMode,
    Category,
    Deny,
    PermissionHook,
    Verdict,
    covered_by_grants,
    decide,
    grant_query,
    tool_category,
)
from .permission_grants import (
    BashGrant,
    GrantQuery,
    NetworkGrant,
    PermissionGrants,
    SharedGrants,
    ToolGrant,
    append_grant,
    host_matches_glob,
    project_grants_path,
    user_grants_path,
)
from .prompt_cache import PROMPT_CACHE_BOUNDARY, PromptCache
from .rerank import LexicalReranker, NoopReranker, Reranker
from .structured import ResponseFormat, json_schema_format, response_format_field, structured_json
from .thread import SmoothAgentThread
from .tool_search import ToolSearch
from .vector import Embedder, HashEmbedder, VectorKnowledge
from .workflow import END, Workflow, WorkflowError, sub_workflow_node

__all__ = [
    "AgentActivities",
    "AgentExecutor",
    "AgentOptions",
    "AgentRunResponse",
    "InProcessActivities",
    "InProcessExecutor",
    "TurnPolicy",
    "drive_turn",
    "Cast",
    "DoneEvent",
    "StreamEvent",
    "TextEvent",
    "ToolCallEvent",
    "ToolResultEvent",
    "usage",
    "Checkpoint",
    "CheckpointStore",
    "Clearance",
    "CostBudget",
    "GATEWAY_COST_HEADERS",
    "CostTracker",
    "DelegateHumanGate",
    "DenyPolicy",
    "DenyPredicate",
    "DenyReason",
    "DenyRules",
    "Embedder",
    "FileRef",
    "load_project_context",
    "parse_file_references",
    "FunctionTool",
    "GatewayLlmProvider",
    "delegate_tool",
    "effective_max_tokens",
    "HashEmbedder",
    "HumanApprovalRequest",
    "HumanApprovalResponse",
    "HumanDecision",
    "HumanGate",
    "InMemoryCheckpointStore",
    "InMemoryKnowledge",
    "InMemoryMemory",
    "Knowledge",
    "KnowledgeHit",
    "LexicalReranker",
    "LlmProvider",
    "Memory",
    "MemoryEntry",
    "NarcAlert",
    "NarcFinding",
    "NarcHook",
    "Severity",
    "has_injection",
    "has_secrets",
    "redact_match",
    "scan_injection",
    "scan_secrets",
    "MockLlmProvider",
    "ModelPricing",
    "parse_gateway_cost",
    "PROMPT_CACHE_BOUNDARY",
    "PromptCache",
    "NoopReranker",
    "json_schema_format",
    "response_format_field",
    "OperatorRole",
    "RecordedCall",
    "Reranker",
    "ResponseFormat",
    "RoleKind",
    "SmoothAgent",
    "SmoothAgentThread",
    "structured_json",
    "Tool",
    "ToolCall",
    "ToolHook",
    "ToolResult",
    "ToolSearch",
    "Usage",
    "Allow",
    "Ask",
    "AutoMode",
    "Category",
    "Deny",
    "PermissionHook",
    "Verdict",
    "covered_by_grants",
    "decide",
    "grant_query",
    "tool_category",
    "BashGrant",
    "GrantQuery",
    "NetworkGrant",
    "PermissionGrants",
    "SharedGrants",
    "ToolGrant",
    "append_grant",
    "host_matches_glob",
    "project_grants_path",
    "user_grants_path",
    "VectorKnowledge",
    "Workflow",
    "WorkflowError",
    "sub_workflow_node",
    "END",
    "scripted_usage",
    "text_response",
    "tool_call_response",
]
