// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

import "time"

// Base shape for every client-to-server WebSocket frame. The `action` field is a
// snake_case verb that selects the handler. `requestId` is chosen by the client
// and echoed back on all related server events so the client can correlate
// responses to pending requests.
type ActionEnvelope struct {
	// The action to perform.
	Action ActionEnvelopeAction `json:"action"`

	// Client-generated correlation ID. Will be echoed back on all related server
	// events. Should be unique per in-flight request. If omitted the server may
	// generate one, but correlating responses becomes the client's problem.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ActionEnvelopeAction string

const ActionEnvelopeActionConfirmToolAction ActionEnvelopeAction = "confirm_tool_action"
const ActionEnvelopeActionCreateConversationSession ActionEnvelopeAction = "create_conversation_session"
const ActionEnvelopeActionGetConversationMessages ActionEnvelopeAction = "get_conversation_messages"
const ActionEnvelopeActionGetSession ActionEnvelopeAction = "get_session"
const ActionEnvelopeActionPing ActionEnvelopeAction = "ping"
const ActionEnvelopeActionSendMessage ActionEnvelopeAction = "send_message"
const ActionEnvelopeActionVerifyOTP ActionEnvelopeAction = "verify_otp"

// A point-in-time snapshot of a smooth-operator agent's state. Checkpoints are
// written by the agent runtime and are used to resume execution after
// interruptions (Lambda cold starts, HITL pauses, network errors). Corresponds to
// the `Checkpoint` struct in the smooth-operator Rust crate.
type Checkpoint struct {
	// The agent whose state is captured in this checkpoint.
	AgentID string `json:"agentId"`

	// ISO 8601 timestamp when the checkpoint was created.
	CreatedAt time.Time `json:"createdAt"`

	// Unique checkpoint identifier (UUID v4).
	ID string `json:"id"`

	// Agent loop iteration counter at the time the checkpoint was taken.
	Iteration int `json:"iteration"`

	// Arbitrary string key/value metadata attached to this checkpoint (e.g. phase
	// name, bead ID).
	Metadata CheckpointMetadata `json:"metadata,omitempty,omitzero"`

	// smooth-operator workflow thread identifier this checkpoint belongs to. Matches
	// `Session.threadId` for the associated session.
	ThreadID string `json:"threadId"`
}

// Arbitrary string key/value metadata attached to this checkpoint (e.g. phase
// name, bead ID).
type CheckpointMetadata map[string]string

// A source the agent used to ground its answer. Each citation points back at one
// retrieved knowledge-base document — the chunk the model read, plus enough
// metadata to render an attribution link. Citations are collected by the runtime
// from the documents that actually grounded a turn (the auto-injected `[Relevant
// knowledge]` context and any `knowledge_search` tool results) and attached to the
// terminal `eventual_response`. For GitHub-sourced documents `url` is the
// blob/issue URL; documents without a web source omit it.
type Citation struct {
	// Stable identifier of the cited source document (the knowledge-base
	// `document_id`). Used to deduplicate citations within a turn.
	ID string `json:"id"`

	// Relevance score of this source for the turn's query (the knowledge-base
	// similarity score). Higher is more relevant.
	Score float64 `json:"score"`

	// The retrieved chunk text that grounded the answer, truncated to a bounded
	// length for display.
	Snippet string `json:"snippet"`

	// Human-readable label for the source — typically the document's source path or,
	// for web-sourced docs, the URL/title.
	Title string `json:"title"`

	// Canonical link to the source, when one exists. For GitHub-sourced documents
	// this is the blob/issue URL stamped onto the document's `source` at ingest (see
	// CONNECTORS.md). Absent for sources with no web location (e.g. uploaded files).
	URL *string `json:"url,omitempty,omitzero"`
}

// Fields sent by the client to approve or reject a pending tool write.
type ConfirmToolActionRequest struct {
	// Action discriminator.
	Action string `json:"action"`

	// True to allow the tool call to proceed; false to reject it. On rejection the
	// agent workflow resumes with an informational context message.
	Approved bool `json:"approved"`

	// Must match the `requestId` from the `write_confirmation_required` event being
	// responded to. This is how the server correlates the confirmation back to the
	// paused workflow.
	RequestID string `json:"requestId"`

	// Session ID of the paused session.
	SessionID string `json:"sessionId"`
}

// No dedicated response — the workflow continuation is signalled by resumed
// streaming events.
type ConfirmToolActionResponse map[string]interface{}

// A single content element within a message. Currently only `text` items are
// defined; additional types (image, file, tool_result) may be added in future
// protocol versions.
type ContentItem struct {
	// The text content (required when type = `text`).
	Text *string `json:"text,omitempty,omitzero"`

	// Content item type discriminator.
	Type ContentItemType `json:"type"`
}

type ContentItemType string

const ContentItemTypeText ContentItemType = "text"

// A conversation thread between participants (users, AI agents, or human agents).
// Corresponds to a row in the `conversations` table. Platform indicates the
// channel on which the conversation takes place.
type Conversation struct {
	// Analytics and scoring data aggregated from messages in this conversation.
	AnalyticsJSON ConversationAnalyticsJSON `json:"analyticsJson,omitempty,omitzero"`

	// ISO 8601 timestamp when the conversation was created.
	CreatedAt time.Time `json:"createdAt"`

	// Unique conversation identifier.
	ID string `json:"id"`

	// Client-provided key that prevents duplicate conversations from being created
	// for the same logical thread.
	IdempotencyKey string `json:"idempotencyKey"`

	// Arbitrary key/value metadata attached to the conversation (e.g. campaign
	// source, CRM fields).
	MetadataJSON ConversationMetadataJSON `json:"metadataJson,omitempty,omitzero"`

	// Human-readable display name for the conversation.
	Name string `json:"name"`

	// The organization that owns this conversation.
	OrganizationID string `json:"organizationId"`

	// The channel on which this conversation takes place.
	Platform ConversationPlatform `json:"platform"`

	// ISO 8601 timestamp when the conversation was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// Analytics and scoring data aggregated from messages in this conversation.
type ConversationAnalyticsJSON map[string]interface{}

// A single message as returned on the wire. This is a subset of the full `Message`
// domain object — it omits server-only fields (metadataJson, analyticsJson) and
// includes abbreviated participant descriptors.
type ConversationMessage struct {
	// Message payload. `text` contains the plain-text form; `structuredResponse`
	// contains parsed agent output when present.
	Content ConversationMessageContent `json:"content"`

	// ISO 8601 timestamp when the message was created.
	CreatedAt time.Time `json:"createdAt"`

	// Message direction: `inbound` = from user, `outbound` = from agent.
	Direction ConversationMessageDirection `json:"direction"`

	// Abbreviated sender descriptor.
	From *ConversationMessageFrom `json:"from,omitempty,omitzero"`

	// Unique message ID.
	ID string `json:"id"`

	// Abbreviated recipient descriptor.
	To *ConversationMessageTo `json:"to,omitempty,omitzero"`
}

// Message payload. `text` contains the plain-text form; `structuredResponse`
// contains parsed agent output when present.
type ConversationMessageContent struct {
	// Structured agent response (shape depends on agent template).
	StructuredResponse *ConversationMessageContentStructuredResponse `json:"structuredResponse,omitempty,omitzero"`

	// Plain-text content.
	Text *string `json:"text,omitempty,omitzero"`
}

// Structured agent response (shape depends on agent template).
type ConversationMessageContentStructuredResponse map[string]interface{}

type ConversationMessageDirection string

const ConversationMessageDirectionInbound ConversationMessageDirection = "inbound"
const ConversationMessageDirectionOutbound ConversationMessageDirection = "outbound"

// Abbreviated sender descriptor.
type ConversationMessageFrom struct {
	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

// Abbreviated recipient descriptor.
type ConversationMessageTo struct {
	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type"`
}

// Arbitrary key/value metadata attached to the conversation (e.g. campaign source,
// CRM fields).
type ConversationMetadataJSON map[string]interface{}

type ConversationPlatform string

const ConversationPlatformDiscord ConversationPlatform = "discord"
const ConversationPlatformEmail ConversationPlatform = "email"
const ConversationPlatformInstagram ConversationPlatform = "instagram"
const ConversationPlatformMessenger ConversationPlatform = "messenger"
const ConversationPlatformPhone ConversationPlatform = "phone"
const ConversationPlatformSlack ConversationPlatform = "slack"
const ConversationPlatformSms ConversationPlatform = "sms"
const ConversationPlatformTiktok ConversationPlatform = "tiktok"
const ConversationPlatformWeb ConversationPlatform = "web"
const ConversationPlatformWhatsapp ConversationPlatform = "whatsapp"

// Fields sent by the client to open a new session.
type CreateConversationSessionRequest struct {
	// Action discriminator.
	Action string `json:"action"`

	// UUID of the agent to start a session with.
	AgentID string `json:"agentId"`

	// Pre-auth context for HMAC-based identity verification. When provided, the
	// server can skip OTP flows by verifying the HMAC signature instead.
	AuthContext *RequestAuthContext `json:"authContext,omitempty,omitzero"`

	// Browser fingerprint string (e.g. from ThumbmarkJS) used for anonymous user
	// correlation across sessions.
	BrowserFingerprint *string `json:"browserFingerprint,omitempty,omitzero"`

	// Arbitrary key/value metadata to attach to the session.
	Metadata RequestMetadata `json:"metadata,omitempty,omitzero"`

	// Client-generated correlation ID echoed back on all related events.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Optional email address for the user participant.
	UserEmail *string `json:"userEmail,omitempty,omitzero"`

	// Optional display name for the user participant.
	UserName *string `json:"userName,omitempty,omitzero"`
}

// Data payload carried in the `immediate_response` event that acknowledges session
// creation.
type CreateConversationSessionResponse struct {
	// ID of the agent handling this session.
	AgentID string `json:"agentId"`

	// Display name of the agent.
	AgentName string `json:"agentName"`

	// Participant ID representing the AI agent in this conversation.
	AgentParticipantID string `json:"agentParticipantId"`

	// ID of the conversation created for this session.
	ConversationID string `json:"conversationId"`

	// Newly created session ID. Use this in all subsequent actions.
	SessionID string `json:"sessionId"`

	// Participant ID representing the user in this conversation.
	UserParticipantID string `json:"userParticipantId"`
}

// Event: `error`. Emitted when an unrecoverable error occurs during request
// processing. The nested `error` object shape (`{ code, message }`) is preserved
// for wire compatibility with clients that destructure `message.error.code`.
// `details` carries additional structured context when available.
type Error struct {
	// Full error payload.
	Data ErrorData `json:"data"`

	// Top-level error object (duplicate of `data.error`; kept for clients that
	// pattern-match on the envelope-level `error` field).
	Error *ErrorError `json:"error,omitempty,omitzero"`

	// Echoes the `requestId` from the originating action, if applicable. Absent for
	// server-initiated errors with no associated request.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// Full error payload.
type ErrorData struct {
	// Optional additional structured error context (e.g. validation issues, partial
	// results).
	Details interface{} `json:"details,omitempty,omitzero"`

	// The error descriptor (nested for wire backward-compatibility).
	Error ErrorDataError `json:"error"`

	// The request ID this error belongs to, if any.
	RequestID *string `json:"requestId,omitempty,omitzero"`
}

// The error descriptor (nested for wire backward-compatibility).
type ErrorDataError struct {
	// Machine-readable error code (e.g. `SESSION_NOT_FOUND`, `RATE_LIMITED`,
	// `VALIDATION_ERROR`, `INTERNAL_ERROR`).
	Code string `json:"code"`

	// Human-readable error description.
	Message string `json:"message"`
}

// Top-level error object (duplicate of `data.error`; kept for clients that
// pattern-match on the envelope-level `error` field).
type ErrorError struct {
	// Machine-readable error code.
	Code string `json:"code"`

	// Human-readable error description.
	Message string `json:"message"`
}

// A structured error descriptor. Used in error events and nested inside event data
// payloads.
type ErrorObject struct {
	// Machine-readable error code (e.g. `SESSION_NOT_FOUND`, `RATE_LIMITED`,
	// `VALIDATION_ERROR`).
	Code string `json:"code"`

	// Human-readable error description.
	Message string `json:"message"`
}

// Base shape for every server-to-client WebSocket frame. `type` is a snake_case
// noun that identifies the event. `requestId` echoes the originating action's
// `requestId` where applicable (may be absent for unsolicited events such as
// `keepalive`). `status` uses HTTP-like codes: 202 = accepted/in-progress, 200 =
// final success, 4xx/5xx = error.
type EventEnvelope struct {
	// Event-specific payload. Shape is defined by the per-event schema in `events/`.
	Data interface{} `json:"data,omitempty,omitzero"`

	// Present on `error` events.
	Error *ErrorObject `json:"error,omitempty,omitzero"`

	// Optional human-readable status description (used in `immediate_response` acks).
	Message *string `json:"message,omitempty,omitzero"`

	// Name of the workflow node that produced this event. Present on `stream_chunk`
	// events.
	Node *string `json:"node,omitempty,omitzero"`

	// Echoes the `requestId` from the originating action. Absent for unsolicited
	// server-push events.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// HTTP-like status code. 202 = acknowledged/in-progress; 200 = final success;
	// 4xx/5xx = error conditions.
	Status *int `json:"status,omitempty,omitzero"`

	// Unix epoch milliseconds. Present on `pong` events and optionally on others.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// A streamed LLM token. Present on `stream_token` events.
	Token *string `json:"token,omitempty,omitzero"`

	// Identifies which event this frame carries.
	Type EventEnvelopeType `json:"type"`
}

type EventEnvelopeType string

const EventEnvelopeTypeError EventEnvelopeType = "error"
const EventEnvelopeTypeEventualResponse EventEnvelopeType = "eventual_response"
const EventEnvelopeTypeImmediateResponse EventEnvelopeType = "immediate_response"
const EventEnvelopeTypeKeepalive EventEnvelopeType = "keepalive"
const EventEnvelopeTypeOTPInvalid EventEnvelopeType = "otp_invalid"
const EventEnvelopeTypeOTPSent EventEnvelopeType = "otp_sent"
const EventEnvelopeTypeOTPVerificationRequired EventEnvelopeType = "otp_verification_required"
const EventEnvelopeTypeOTPVerified EventEnvelopeType = "otp_verified"
const EventEnvelopeTypePong EventEnvelopeType = "pong"
const EventEnvelopeTypeStreamChunk EventEnvelopeType = "stream_chunk"
const EventEnvelopeTypeStreamToken EventEnvelopeType = "stream_token"
const EventEnvelopeTypeWriteConfirmationRequired EventEnvelopeType = "write_confirmation_required"

// Event: `eventual_response`. The terminal event of a streaming turn. Emitted
// after the agent workflow completes and its output has been persisted. Clients
// should treat this as the authoritative final state for the turn and may discard
// intermediate `stream_chunk` / `stream_token` data. Status is always 200 on
// success.
type EventualResponse struct {
	// The terminal response payload.
	Data EventualResponseData `json:"data"`

	// Echoes the `requestId` from the originating `send_message` action.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// HTTP-like status. Always 200 for a successful eventual response.
	Status *int `json:"status,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// The terminal response payload.
type EventualResponseData struct {
	// The final agent output.
	Data EventualResponseDataData `json:"data"`

	// The request ID this response belongs to.
	RequestID string `json:"requestId"`

	// HTTP-like status. Typically 200.
	Status int `json:"status"`
}

// The final agent output.
type EventualResponseDataData struct {
	// The sources that grounded this answer, when any were retrieved. Collected by
	// the runtime from the documents that actually grounded the turn — the
	// auto-injected `[Relevant knowledge]` context and any `knowledge_search` tool
	// results — deduplicated by source id and capped. Optional and back-compatible:
	// absent when the turn used no knowledge sources. Each item is a `Citation` (see
	// `domain/citation.schema.json`).
	Citations []EventualResponseDataDataCitationsElem `json:"citations,omitempty,omitzero"`

	// Human-readable escalation reason when `needsEscalation` is true.
	EscalationReason *string `json:"escalationReason,omitempty,omitzero"`

	// ID of the agent message as persisted to the `conversation_messages` table.
	MessageID string `json:"messageId"`

	// True if the agent flagged this conversation for human escalation.
	NeedsEscalation *bool `json:"needsEscalation,omitempty,omitzero"`

	// The structured agent response payload. Shape depends on the agent template.
	// Clients should validate against a template-specific schema before rendering.
	Response interface{} `json:"response"`
}

// A source the agent used to ground its answer (a `Citation` — see
// `domain/citation.schema.json`). For GitHub-sourced documents `url` is the
// blob/issue URL; documents without a web source omit it.
type EventualResponseDataDataCitationsElem struct {
	// Stable identifier of the cited source document (the knowledge-base
	// `document_id`). Used to deduplicate citations within a turn.
	ID string `json:"id"`

	// Relevance score of this source for the turn's query (the knowledge-base
	// similarity score). Higher is more relevant.
	Score float64 `json:"score"`

	// The retrieved chunk text that grounded the answer, truncated to a bounded
	// length for display.
	Snippet string `json:"snippet"`

	// Human-readable label for the source — typically the document's source path or,
	// for web-sourced docs, the URL/title.
	Title string `json:"title"`

	// Canonical link to the source, when one exists. For GitHub-sourced documents
	// this is the blob/issue URL stamped onto the document's `source` at ingest.
	// Absent for sources with no web location.
	URL *string `json:"url,omitempty,omitzero"`
}

// Structured output from the default general-purpose agent template. Agents built
// on custom templates may extend or replace this shape.
type GeneralAgentResponse struct {
	// Estimated customer happiness for this turn (0 = very unhappy, 1 = very happy).
	CustomerHappinessScore float64 `json:"customerHappinessScore"`

	// Estimated degree to which the customer's needs were met (0 = not met, 1 = fully
	// met).
	NeedsSatisfactionScore float64 `json:"needsSatisfactionScore"`

	// One-sentence summary of what the user requested.
	RequestSummary string `json:"requestSummary"`

	// The agent's assessment of where the conversation stands after this turn.
	ResolutionStatus GeneralAgentResponseResolutionStatus `json:"resolutionStatus"`

	// Ordered text segments that together form the agent's reply. Clients may join
	// them or render each separately.
	ResponseParts []string `json:"responseParts"`

	// Ordered list of suggested follow-up actions the client UI may surface to the
	// user.
	SuggestedNextActions []string `json:"suggestedNextActions"`
}

type GeneralAgentResponseResolutionStatus string

const GeneralAgentResponseResolutionStatusBlocked GeneralAgentResponseResolutionStatus = "blocked"
const GeneralAgentResponseResolutionStatusInProgress GeneralAgentResponseResolutionStatus = "in_progress"
const GeneralAgentResponseResolutionStatusNeedsMoreInfo GeneralAgentResponseResolutionStatus = "needs_more_info"
const GeneralAgentResponseResolutionStatusRequiresEscalation GeneralAgentResponseResolutionStatus = "requires_escalation"
const GeneralAgentResponseResolutionStatusResolved GeneralAgentResponseResolutionStatus = "resolved"

// Fields sent by the client to page through conversation history.
type GetMessagesRequest struct {
	// Action discriminator.
	Action string `json:"action"`

	// ISO 8601 cursor: return only messages created strictly before this timestamp.
	// Omit to start from the most recent message.
	Before *time.Time `json:"before,omitempty,omitzero"`

	// Maximum number of messages to return per page. Must be 1–100; defaults to 50.
	Limit int `json:"limit,omitempty,omitzero"`

	// Client-generated correlation ID echoed back on all related events.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Session ID whose conversation messages to fetch.
	SessionID string `json:"sessionId"`
}

// Data payload carried in the `immediate_response` event.
type GetMessagesResponse struct {
	// True if more messages exist before the oldest message in this page. Use the
	// oldest `createdAt` as the next `before` cursor.
	HasMore bool `json:"hasMore"`

	// Ordered list of messages (newest-first up to `limit`).
	Messages []ConversationMessage `json:"messages"`
}

// Fields sent by the client to retrieve a session.
type GetSessionRequest struct {
	// Action discriminator.
	Action string `json:"action"`

	// Client-generated correlation ID echoed back on all related events.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// ID of the session to retrieve.
	SessionID string `json:"sessionId"`
}

// Data payload carried in the `immediate_response` event. Field set matches
// `Session` in `domain/session.schema.json` (wire-subset; full domain object may
// include additional server-only fields).
type GetSessionResponse struct {
	// Agent ID.
	AgentID string `json:"agentId"`

	// Display name of the agent.
	AgentName string `json:"agentName"`

	// Participant ID for the agent in this session.
	AgentParticipantID string `json:"agentParticipantId"`

	// Conversation ID.
	ConversationID string `json:"conversationId"`

	// Session ID.
	SessionID string `json:"sessionId"`

	// Current lifecycle status of the session.
	Status *ResponseStatus `json:"status,omitempty,omitzero"`

	// smooth-operator thread identifier. Present when the session has an associated
	// workflow thread.
	ThreadID *string `json:"threadId,omitempty,omitzero"`

	// Participant ID for the user in this session.
	UserParticipantID string `json:"userParticipantId"`
}

// Event: `immediate_response`. Sent by the server synchronously upon receiving any
// action, to acknowledge that the request was accepted and processing has begun.
// For streaming actions (`send_message`) this always precedes `stream_chunk` /
// `stream_token` events and the final `eventual_response`. For non-streaming
// actions (e.g. `get_session`, `create_conversation_session`) this also carries
// the complete response payload in `data`.
type ImmediateResponse struct {
	// Action-specific response payload. For `create_conversation_session` and
	// `get_session`, this is the session descriptor. For `get_conversation_messages`,
	// this is the message page. For streaming `send_message`, this is typically empty
	// or contains only a minimal ack.
	Data ImmediateResponseData `json:"data"`

	// Human-readable status description (e.g. `Processing your request...`).
	Message *string `json:"message,omitempty,omitzero"`

	// Echoes the `requestId` from the originating action.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// HTTP-like status. 202 = accepted and processing; 200 = synchronous success
	// (non-streaming responses).
	Status *int `json:"status,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// Action-specific response payload. For `create_conversation_session` and
// `get_session`, this is the session descriptor. For `get_conversation_messages`,
// this is the message page. For streaming `send_message`, this is typically empty
// or contains only a minimal ack.
type ImmediateResponseData map[string]interface{}

// Event: `keepalive`. Sent periodically by the server during long-running agent
// turns (typically every 30 seconds) to prevent AWS API Gateway's 10-minute idle
// connection timeout from closing the WebSocket while the backend is still
// computing. Clients should acknowledge receipt by updating their last-seen
// timestamp, but no reply action is needed. Distinct from `ping`/`pong` which are
// client-initiated.
type Keepalive struct {
	// Keepalive payload.
	Data KeepaliveData `json:"data"`

	// The `requestId` of the in-flight request this keepalive is associated with.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Unix epoch milliseconds when the keepalive was sent.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// Keepalive payload.
type KeepaliveData struct {
	// The request ID of the in-flight request this keepalive belongs to.
	RequestID string `json:"requestId"`
}

// A single message within a conversation. Direction is from the conversation's
// perspective: `inbound` = arriving from the user/external party; `outbound` =
// sent by the agent or platform. Corresponds to a row in the
// `conversation_messages` table.
type Message struct {
	// Analytics data associated with this message (e.g. sentiment scores, token
	// counts).
	AnalyticsJSON *MessageAnalyticsJSON `json:"analyticsJson,omitempty,omitzero"`

	// The message payload.
	Content MessageContent `json:"content"`

	// The conversation this message belongs to.
	ConversationID MessageConversationID `json:"conversationId,omitempty,omitzero"`

	// ISO 8601 timestamp when the message was created.
	CreatedAt time.Time `json:"createdAt"`

	// Message direction relative to the platform: `inbound` = from user/external,
	// `outbound` = from agent/platform.
	Direction MessageDirection `json:"direction"`

	// ID assigned by an external platform (e.g. a Twilio SID or Messenger message
	// id).
	ExternalID MessageExternalID `json:"externalId,omitempty,omitzero"`

	// Abbreviated sender descriptor (wire shape used in API responses; full
	// participant data lives in domain/participant.schema.json).
	From *MessageFrom `json:"from,omitempty,omitzero"`

	// Unique message identifier.
	ID string `json:"id"`

	// Arbitrary key/value metadata attached to this message.
	MetadataJSON *MessageMetadataJSON `json:"metadataJson,omitempty,omitzero"`

	// The organization that owns this message.
	OrganizationID MessageOrganizationID `json:"organizationId,omitempty,omitzero"`

	// Abbreviated recipient descriptor.
	To *MessageTo `json:"to,omitempty,omitzero"`

	// ISO 8601 timestamp when the message was last updated.
	UpdatedAt MessageUpdatedAt `json:"updatedAt,omitempty,omitzero"`
}

// Analytics data associated with this message (e.g. sentiment scores, token
// counts).
type MessageAnalyticsJSON map[string]interface{}

// Structured content of a message. Currently always contains `items`; `text` and
// `structuredResponse` are the two supported item types.
type MessageContent struct {
	// Ordered list of content items that make up this message.
	Items []ContentItem `json:"items,omitempty,omitzero"`

	// Structured agent response payload. Shape varies by agent template.
	StructuredResponse *MessageContentStructuredResponse `json:"structuredResponse,omitempty,omitzero"`

	// Convenience flat-text representation of the message (populated for simple
	// text-only messages).
	Text MessageContentText `json:"text,omitempty,omitzero"`
}

// Structured agent response payload. Shape varies by agent template.
type MessageContentStructuredResponse map[string]interface{}

// Convenience flat-text representation of the message (populated for simple
// text-only messages).
type MessageContentText *string

// The conversation this message belongs to.
type MessageConversationID *string

type MessageDirection string

const MessageDirectionInbound MessageDirection = "inbound"
const MessageDirectionOutbound MessageDirection = "outbound"

// ID assigned by an external platform (e.g. a Twilio SID or Messenger message id).
type MessageExternalID *string

// Abbreviated sender descriptor (wire shape used in API responses; full
// participant data lives in domain/participant.schema.json).
type MessageFrom struct {
	// Participant ID of the sender.
	ID string `json:"id"`

	// Display name of the sender.
	Name MessageFromName `json:"name,omitempty,omitzero"`

	// Participant type of the sender.
	Type string `json:"type"`
}

// Display name of the sender.
type MessageFromName *string

// Arbitrary key/value metadata attached to this message.
type MessageMetadataJSON map[string]interface{}

// The organization that owns this message.
type MessageOrganizationID *string

// Abbreviated recipient descriptor.
type MessageTo struct {
	// Participant ID of the recipient.
	ID string `json:"id"`

	// Display name of the recipient.
	Name MessageToName `json:"name,omitempty,omitzero"`

	// Participant type of the recipient.
	Type string `json:"type"`
}

// Display name of the recipient.
type MessageToName *string

// ISO 8601 timestamp when the message was last updated.
type MessageUpdatedAt *time.Time

// Event: `otp_invalid`. Emitted when the caller's OTP attempt is rejected — wrong
// code, expired, max attempts reached, or record not found. When
// `attemptsRemaining` is 0 the session is locked; the client must restart the OTP
// flow. When greater than 0 the client may prompt the user to try again.
type OTPInvalid struct {
	// Failure details.
	Data OTPInvalidData `json:"data"`

	// Echoes the `requestId` from the originating `verify_otp` action.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// Failure details.
type OTPInvalidData struct {
	// OTP invalid payload.
	Data OTPInvalidDataData `json:"data"`

	// The request ID this verification belongs to.
	RequestID string `json:"requestId"`
}

// OTP invalid payload.
type OTPInvalidDataData struct {
	// How many more attempts the caller has before the OTP is locked. Zero means the
	// session is locked and a new OTP must be requested.
	AttemptsRemaining int `json:"attemptsRemaining"`

	// Machine-readable failure reason. Absent if the server cannot determine a
	// specific cause.
	Error *OTPInvalidDataDataError `json:"error,omitempty,omitzero"`

	// Human-readable failure message suitable for display in the verification UI.
	Message string `json:"message"`
}

type OTPInvalidDataDataError string

const OTPInvalidDataDataErrorEXPIRED OTPInvalidDataDataError = "EXPIRED"
const OTPInvalidDataDataErrorINVALIDCODE OTPInvalidDataDataError = "INVALID_CODE"
const OTPInvalidDataDataErrorMAXATTEMPTS OTPInvalidDataDataError = "MAX_ATTEMPTS"
const OTPInvalidDataDataErrorNOTFOUND OTPInvalidDataDataError = "NOT_FOUND"

// Event: `otp_sent`. Acknowledgement that an OTP code has been dispatched to the
// user via the chosen delivery channel. The client should update the UI to prompt
// the user to enter the code they received.
type OTPSent struct {
	// OTP send acknowledgement details.
	Data OTPSentData `json:"data"`

	// Echoes the `requestId` from the originating action.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// OTP send acknowledgement details.
type OTPSentData struct {
	// Delivery details.
	Data OTPSentDataData `json:"data"`

	// The request ID this OTP delivery belongs to.
	RequestID string `json:"requestId"`
}

// Delivery details.
type OTPSentDataData struct {
	// The channel through which the OTP was delivered.
	Channel OTPSentDataDataChannel `json:"channel"`

	// Partially masked destination address for display in the UI (e.g.
	// `j***@example.com` or `+1 ***-***-4567`). Sufficient for the user to recognize
	// their own address without exposing it fully.
	MaskedDestination string `json:"maskedDestination"`
}

type OTPSentDataDataChannel string

const OTPSentDataDataChannelEmail OTPSentDataDataChannel = "email"
const OTPSentDataDataChannelSms OTPSentDataDataChannel = "sms"

// Event: `otp_verification_required`. Emitted when the agent workflow pauses
// because it needs the caller to complete OTP verification before proceeding with
// an authenticated action. Corresponds to smooth-operator's
// `AgentEvent::HumanInputRequired { Input }` for auth gates. The client should
// surface a channel-selection and OTP input UI. After the user selects a channel,
// the client may trigger OTP delivery via a separate flow; the `verify_otp` action
// submits the received code.
type OTPVerificationRequired struct {
	// Verification prompt details.
	Data OTPVerificationRequiredData `json:"data"`

	// Echoes the `requestId` from the originating `send_message` action. Must be
	// included in the `verify_otp` reply.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// Verification prompt details.
type OTPVerificationRequiredData struct {
	// Details about the authentication requirement.
	Data OTPVerificationRequiredDataData `json:"data"`

	// The request ID this verification belongs to.
	RequestID string `json:"requestId"`
}

// Details about the authentication requirement.
type OTPVerificationRequiredDataData struct {
	// Human-readable description of the action requiring verification, suitable for
	// the consent UI.
	ActionDescription string `json:"actionDescription"`

	// Required authentication level. Common values: `email`, `sms`, `mfa`,
	// `end_user`, `admin`.
	AuthLevel string `json:"authLevel"`

	// Delivery channels available to send the OTP. The client should let the user
	// choose.
	AvailableChannels []OTPVerificationRequiredDataDataAvailableChannelsElem `json:"availableChannels"`

	// Opaque identifier of the tool invocation awaiting verification.
	ToolID string `json:"toolId"`
}

type OTPVerificationRequiredDataDataAvailableChannelsElem string

const OTPVerificationRequiredDataDataAvailableChannelsElemEmail OTPVerificationRequiredDataDataAvailableChannelsElem = "email"
const OTPVerificationRequiredDataDataAvailableChannelsElemSms OTPVerificationRequiredDataDataAvailableChannelsElem = "sms"

// Event: `otp_verified`. Emitted when the caller's OTP attempt succeeds, or when a
// pre-auth HMAC makes OTP unnecessary. The session is now authenticated at the
// required level and the paused agent workflow resumes. A streaming sequence
// (`stream_chunk` / `stream_token` → `eventual_response`) follows.
type OTPVerified struct {
	// Verification success details.
	Data OTPVerifiedData `json:"data"`

	// Echoes the `requestId` from the originating `verify_otp` action.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// Verification success details.
type OTPVerifiedData struct {
	// Success payload.
	Data OTPVerifiedDataData `json:"data"`

	// The request ID this verification belongs to.
	RequestID string `json:"requestId"`
}

// Success payload.
type OTPVerifiedDataData struct {
	// Short human-readable confirmation message (e.g. `Identity verified
	// successfully.`).
	Message string `json:"message"`
}

// A participant in a conversation. Participants may be end users, AI agents, or
// human support agents. Corresponds to a row in the `conversation_participants`
// table.
type Participant struct {
	// Browser fingerprint (ThumbmarkJS) for anonymous user identification.
	BrowserFingerprint ParticipantBrowserFingerprint `json:"browserFingerprint,omitempty,omitzero"`

	// Parsed browser / device metadata collected at session start.
	BrowserInfo *ParticipantBrowserInfo `json:"browserInfo,omitempty,omitzero"`

	// The conversation this participant belongs to.
	ConversationID string `json:"conversationId"`

	// ISO 8601 timestamp when the participant record was created.
	CreatedAt time.Time `json:"createdAt"`

	// Foreign key into the CRM contacts table if this participant has been matched.
	CrmContactID ParticipantCrmContactID `json:"crmContactId,omitempty,omitzero"`

	// Email address if known.
	Email ParticipantEmail `json:"email,omitempty,omitzero"`

	// External identity (e.g. Supabase auth user UUID) for authenticated
	// participants.
	ExternalID ParticipantExternalID `json:"externalId,omitempty,omitzero"`

	// Unique participant identifier.
	ID string `json:"id"`

	// Internal system identifier (e.g. agent UUID from the agents table).
	InternalID ParticipantInternalID `json:"internalId,omitempty,omitzero"`

	// Arbitrary key/value metadata attached to this participant.
	MetadataJSON ParticipantMetadataJSON `json:"metadataJson,omitempty,omitzero"`

	// Display name for this participant.
	Name string `json:"name"`

	// The organization that owns this participant record.
	OrganizationID string `json:"organizationId"`

	// Phone number in E.164 format if known.
	Phone ParticipantPhone `json:"phone,omitempty,omitzero"`

	// Participant role: `user` = end-user, `ai-agent` = smooth-operator agent,
	// `human-agent` = live support agent.
	Type ParticipantType `json:"type"`

	// ISO 8601 timestamp when the participant record was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// Browser fingerprint (ThumbmarkJS) for anonymous user identification.
type ParticipantBrowserFingerprint *string

// Parsed browser / device metadata collected at session start.
type ParticipantBrowserInfo map[string]interface{}

// Foreign key into the CRM contacts table if this participant has been matched.
type ParticipantCrmContactID *string

// Email address if known.
type ParticipantEmail *string

// External identity (e.g. Supabase auth user UUID) for authenticated participants.
type ParticipantExternalID *string

// Internal system identifier (e.g. agent UUID from the agents table).
type ParticipantInternalID *string

// Arbitrary key/value metadata attached to this participant.
type ParticipantMetadataJSON map[string]interface{}

// Phone number in E.164 format if known.
type ParticipantPhone *string

type ParticipantType string

const ParticipantTypeAiAgent ParticipantType = "ai-agent"
const ParticipantTypeHumanAgent ParticipantType = "human-agent"
const ParticipantTypeUser ParticipantType = "user"

// A ping frame. Only `action` and the optional `requestId` are required.
type PingRequest struct {
	// Action discriminator.
	Action string `json:"action"`

	// Client-generated correlation ID echoed back in the `pong` event.
	RequestID *string `json:"requestId,omitempty,omitzero"`
}

// Event: `pong`. The server's reply to a `ping` action. Carries the server's
// current Unix epoch timestamp in milliseconds. Clients use the round-trip time to
// detect zombie connections.
type Pong struct {
	// Pong payload (mirrors top-level `timestamp` for clients that only inspect
	// `data`).
	Data *PongData `json:"data,omitempty,omitzero"`

	// Echoes the `requestId` from the originating `ping` action.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Server-side Unix epoch milliseconds when the pong was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// Pong payload (mirrors top-level `timestamp` for clients that only inspect
// `data`).
type PongData struct {
	// Server-side Unix epoch milliseconds.
	Timestamp int `json:"timestamp"`
}

// Data payload carried in the `pong` event.
type PongResponse struct {
	// Server-side Unix epoch milliseconds when the pong was sent.
	Timestamp int `json:"timestamp"`
}

// Pre-auth context for HMAC-based identity verification. When provided, the server
// can skip OTP flows by verifying the HMAC signature instead.
type RequestAuthContext struct {
	// HMAC-SHA256 signature over `userId + timestamp` using a shared secret.
	Signature string `json:"signature"`

	// Unix epoch seconds when the HMAC was signed. Used for replay protection
	// (typical max age: 60s).
	Timestamp int `json:"timestamp"`

	// The user's identity claim.
	UserID string `json:"userId"`
}

// Arbitrary key/value metadata to attach to the session.
type RequestMetadata map[string]interface{}

type ResponseStatus string

const ResponseStatusActive ResponseStatus = "active"
const ResponseStatusEnded ResponseStatus = "ended"
const ResponseStatusIdle ResponseStatus = "idle"

// Fields sent by the client to submit a message.
type SendMessageRequest struct {
	// Action discriminator.
	Action string `json:"action"`

	// The user's message text. Between 1 and 10 000 characters.
	Message string `json:"message"`

	// Client-generated correlation ID echoed back on all related events.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Session ID returned by `create_conversation_session`.
	SessionID string `json:"sessionId"`

	// Whether to receive incremental `stream_chunk` and `stream_token` events.
	// Defaults to `true`. Set to `false` to receive only the final
	// `eventual_response`.
	Stream bool `json:"stream,omitempty,omitzero"`
}

// Data payload carried in the terminal `eventual_response` event for this action.
// Also see `GeneralAgentResponse` for the structured response shape.
type SendMessageResponse struct {
	// Human-readable reason when `needsEscalation` is true.
	EscalationReason *string `json:"escalationReason,omitempty,omitzero"`

	// ID of the agent's response message as persisted to the database.
	MessageID string `json:"messageId"`

	// True if the agent flagged this turn for human escalation.
	NeedsEscalation bool `json:"needsEscalation"`

	// Structured agent response.
	Response GeneralAgentResponse `json:"response"`
}

// An AI conversation session. Ties together a conversation, an agent, the user and
// agent participants, and the smooth-operator workflow thread. Corresponds to a
// row in the `conversation_sessions` table. The `threadId` field is the
// smooth-operator thread identifier (stored as `langgraph_thread_id` in the DB for
// historical reasons; renamed to `threadId` in the protocol).
type Session struct {
	// The agent handling this session.
	AgentID string `json:"agentId"`

	// Human-readable display name of the agent.
	AgentName string `json:"agentName"`

	// The participant record representing the AI agent in this session.
	AgentParticipantID string `json:"agentParticipantId"`

	// The conversation this session is attached to.
	ConversationID string `json:"conversationId"`

	// ISO 8601 timestamp when the session was created.
	CreatedAt *time.Time `json:"createdAt,omitempty,omitzero"`

	// ISO 8601 timestamp when the session ended, or null if still active.
	EndedAt SessionEndedAt `json:"endedAt,omitempty,omitzero"`

	// ISO 8601 timestamp of the most recent activity (message, keepalive, etc.).
	LastActivityAt *time.Time `json:"lastActivityAt,omitempty,omitzero"`

	// Number of messages exchanged in this session.
	MessageCount *int `json:"messageCount,omitempty,omitzero"`

	// Arbitrary key/value metadata attached to this session (e.g. browser info,
	// campaign source).
	Metadata SessionMetadata `json:"metadata,omitempty,omitzero"`

	// Unique session identifier.
	SessionID string `json:"sessionId"`

	// Lifecycle status of the session.
	Status *SessionStatus `json:"status,omitempty,omitzero"`

	// smooth-operator workflow thread identifier. Used to resume agent state across
	// turns and process restarts. Stored as `langgraph_thread_id` in the database for
	// historical reasons.
	ThreadID string `json:"threadId"`

	// Cumulative token count consumed in this session.
	TokenCount *int `json:"tokenCount,omitempty,omitzero"`

	// ISO 8601 timestamp when the session was last updated.
	UpdatedAt *time.Time `json:"updatedAt,omitempty,omitzero"`

	// The participant record representing the end user in this session.
	UserParticipantID string `json:"userParticipantId"`
}

// ISO 8601 timestamp when the session ended, or null if still active.
type SessionEndedAt *time.Time

// Arbitrary key/value metadata attached to this session (e.g. browser info,
// campaign source).
type SessionMetadata map[string]interface{}

type SessionStatus string

const SessionStatusActive SessionStatus = "active"
const SessionStatusEnded SessionStatus = "ended"
const SessionStatusIdle SessionStatus = "idle"

// Event: `stream_chunk`. Emitted each time a node in the smooth-operator workflow
// completes. Carries the node name and a filtered state snapshot. Clients use this
// to show per-node progress (e.g. `knowledge_search completed`, tool activity) in
// an agent team view. Distinct from `stream_token` which carries raw token deltas;
// a `stream_chunk` typically fires once per node while multiple `stream_token`
// events may fire within a single node's LLM call.
type StreamChunk struct {
	// The per-node state snapshot.
	Data StreamChunkData `json:"data"`

	// Name of the workflow node that just completed and produced this chunk.
	Node *string `json:"node,omitempty,omitzero"`

	// Echoes the `requestId` from the originating `send_message` action.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// The per-node state snapshot.
type StreamChunkData struct {
	// Reserved for future use. When true, this is the last `stream_chunk` for the
	// request. Currently clients should use `eventual_response` to detect stream
	// completion.
	Done *bool `json:"done,omitempty,omitzero"`

	// Name of the workflow node that produced this state snapshot.
	Node string `json:"node"`

	// The request ID this chunk belongs to.
	RequestID string `json:"requestId"`

	// Filtered subset of the node's output state exposed to the client. Only
	// safe-to-expose fields are included; server-internal state is stripped.
	State StreamChunkDataState `json:"state"`
}

// Filtered subset of the node's output state exposed to the client. Only
// safe-to-expose fields are included; server-internal state is stripped.
type StreamChunkDataState struct {
	// Non-null when the workflow has paused awaiting OTP verification. Clients should
	// surface an OTP input UI.
	PendingOTPVerification *StreamChunkDataStatePendingOTPVerification `json:"pendingOtpVerification,omitempty,omitzero"`

	// Non-null when the workflow has paused awaiting user confirmation of a write
	// operation. Clients should surface a confirmation UI.
	PendingWriteConfirmation *StreamChunkDataStatePendingWriteConfirmation `json:"pendingWriteConfirmation,omitempty,omitzero"`

	// Unstructured LLM output from this node, if any.
	RawResponse interface{} `json:"rawResponse,omitempty,omitzero"`

	// Parsed structured response from this node, if any.
	StructuredResponse interface{} `json:"structuredResponse,omitempty,omitzero"`
}

// Non-null when the workflow has paused awaiting OTP verification. Clients should
// surface an OTP input UI.
type StreamChunkDataStatePendingOTPVerification map[string]interface{}

// Non-null when the workflow has paused awaiting user confirmation of a write
// operation. Clients should surface a confirmation UI.
type StreamChunkDataStatePendingWriteConfirmation map[string]interface{}

// Event: `stream_token`. A single LLM output token forwarded to the client in real
// time. Corresponds to smooth-operator's `AgentEvent::TokenDelta`. Clients
// accumulate tokens to display a live typing animation. After the node finishes, a
// `stream_chunk` event carries the complete state snapshot for that node.
type StreamToken struct {
	// Token event payload.
	Data StreamTokenData `json:"data"`

	// Echoes the `requestId` from the originating `send_message` action.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// The raw token text. Also present inside `data.token` for consumers that only
	// inspect `data`.
	Token *string `json:"token,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// Token event payload.
type StreamTokenData struct {
	// The request ID this token belongs to.
	RequestID string `json:"requestId"`

	// The raw token text.
	Token string `json:"token"`
}

// Fields sent by the client to submit an OTP code.
type VerifyOTPRequest struct {
	// Action discriminator.
	Action string `json:"action"`

	// The one-time password code entered by the user.
	Code string `json:"code"`

	// Must match the `requestId` from the `otp_verification_required` event being
	// responded to.
	RequestID string `json:"requestId"`

	// Session ID of the paused session.
	SessionID string `json:"sessionId"`
}

// No dedicated response — outcome signalled by `otp_verified` or `otp_invalid`
// events.
type VerifyOTPResponse map[string]interface{}

// Event: `write_confirmation_required`. Emitted when the agent workflow pauses
// before running a state-mutating tool call that requires explicit user approval.
// Corresponds to smooth-operator's `AgentEvent::HumanInputRequired { Confirm }`.
// The client must surface a confirmation dialog and reply with a
// `confirm_tool_action` action using the same `requestId`. Until the client
// responds, the workflow remains paused.
type WriteConfirmationRequired struct {
	// Confirmation prompt details.
	Data WriteConfirmationRequiredData `json:"data"`

	// Echoes the `requestId` from the originating `send_message` action. Must be
	// included in the `confirm_tool_action` reply.
	RequestID *string `json:"requestId,omitempty,omitzero"`

	// Unix epoch milliseconds when the event was emitted.
	Timestamp *int `json:"timestamp,omitempty,omitzero"`

	// Event type discriminator.
	Type string `json:"type"`
}

// Confirmation prompt details.
type WriteConfirmationRequiredData struct {
	// Details about the pending write that the user must approve or reject.
	Data WriteConfirmationRequiredDataData `json:"data"`

	// The request ID this confirmation belongs to.
	RequestID string `json:"requestId"`
}

// Details about the pending write that the user must approve or reject.
type WriteConfirmationRequiredDataData struct {
	// Human-readable description of the action the agent wants to perform, suitable
	// for displaying in a confirmation dialog (e.g. `Delete contact John Doe
	// (john@example.com)`).
	ActionDescription string `json:"actionDescription"`

	// Opaque identifier of the tool invocation awaiting confirmation. Provided for
	// correlation; clients do not need to parse or display this.
	ToolID string `json:"toolId"`
}
